// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using System;
using System.Data;
using System.Linq;
//using SecureAccess.Models;
using PETAS.Models.Domain.SecureAccess;

namespace SecureAccess.Models
{
    public partial class SecureaccessContext
    {

        [DbFunction("DateTimeMax", "dbo")]
        public static DateTime? DateTimeMax(DateTime? DateTime1, DateTime? DateTime2)
        {
            throw new NotSupportedException("This method can only be called from Entity Framework Core queries");
        }

        [DbFunction("DateTimeMin", "dbo")]
        public static DateTime? DateTimeMin(DateTime? DateTime1, DateTime? DateTime2)
        {
            throw new NotSupportedException("This method can only be called from Entity Framework Core queries");
        }

        [DbFunction("GetFullName", "dbo")]
        public static string GetFullName(string FirstName, string LastName, string OtherNames)
        {
            throw new NotSupportedException("This method can only be called from Entity Framework Core queries");
        }

        [DbFunction("GetParentFromTransitivePath", "dbo")]
        public static int? GetParentFromTransitivePath(string TransitivePath, int? ChildObjectID)
        {
            throw new NotSupportedException("This method can only be called from Entity Framework Core queries");
        }

        [DbFunction("GetUserAppAccess", "dbo")]
        public static int? GetUserAppAccess(string Alias, int? Count, int? ObjectID)
        {
            throw new NotSupportedException("This method can only be called from Entity Framework Core queries");
        }

        [DbFunction("GetUserName", "dbo")]
        public static string GetUserName(int? objectid)
        {
            throw new NotSupportedException("This method can only be called from Entity Framework Core queries");
        }

        [DbFunction("ProperCase", "dbo")]
        public static string ProperCase(string Text)
        {
            throw new NotSupportedException("This method can only be called from Entity Framework Core queries");
        }

        protected void OnModelCreatingGeneratedFunctions(ModelBuilder modelBuilder)
        {
        }
    }
}
