// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace PETAS.Models.Domain.HRMS
{
    [Table("Employee")]
    public partial class Employee
    {
        [Key]
        [Column("EmployeeID")]
        public int EmployeeId { get; set; }
        [StringLength(50)]
        public string FirstName { get; set; }
        [StringLength(50)]
        public string LastName { get; set; }
        [StringLength(50)]
        public string OtherNames { get; set; }
        [StringLength(255)]
        public string Address1 { get; set; }
        [StringLength(255)]
        public string Address2 { get; set; }
        [StringLength(50)]
        public string EmailAddress { get; set; }
        [StringLength(50)]
        public string Phone { get; set; }
        [StringLength(50)]
        public string Mobile { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? DateOfBirth { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? DateOfRecruitment { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? DateOfRetirement { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? DateOfExit { get; set; }
        [Column("StaffID")]
        [StringLength(10)]
        public string StaffId { get; set; }
        [Column("GenderID")]
        public int? GenderId { get; set; }
        [Column("ReligionID")]
        public int? ReligionId { get; set; }
        [Column("MaritalStatusID")]
        public int? MaritalStatusId { get; set; }
        [Column("DepartmentID")]
        public int? DepartmentId { get; set; }
        [Column("JobTitleID")]
        public int? JobTitleId { get; set; }
        [Column("CategoryID")]
        public int? CategoryId { get; set; }
        [Column("GradeID")]
        public int? GradeId { get; set; }
        [Column("GroupID")]
        public int? GroupId { get; set; }
        [Column("ClassID")]
        public int? ClassId { get; set; }
        [Column("QuartileID")]
        public int? QuartileId { get; set; }
        [Column("BranchID")]
        public int? BranchId { get; set; }
        [Column("StatusID")]
        public int? StatusId { get; set; }
        [Column("HealthInsuranceID")]
        public int? HealthInsuranceId { get; set; }
        [Column("HealthInsuranceCategoryID")]
        public int? HealthInsuranceCategoryId { get; set; }
        [StringLength(30)]
        public string HealthInsuranceNumber { get; set; }
        [StringLength(30)]
        public string BankAccountNumber { get; set; }
        [Column("TaxIDNumber")]
        [StringLength(30)]
        public string TaxIdnumber { get; set; }
        [Column("NationalIDNumber")]
        [StringLength(30)]
        public string NationalIdnumber { get; set; }
        [Column("SSFNumber")]
        [StringLength(30)]
        public string Ssfnumber { get; set; }
        [Column("SSFContribution", TypeName = "decimal(18, 4)")]
        public decimal? Ssfcontribution { get; set; }
        [Column("SSFEmployerContribution", TypeName = "decimal(18, 4)")]
        public decimal? SsfemployerContribution { get; set; }
        [Column("IsPFMember")]
        public bool? IsPfmember { get; set; }
        [Column("PFNumber")]
        [StringLength(30)]
        public string Pfnumber { get; set; }
        [Column("PFT2Number")]
        [StringLength(30)]
        public string Pft2number { get; set; }
        [Column("PFT3Number")]
        [StringLength(30)]
        public string Pft3number { get; set; }
        [Column("PFContribution", TypeName = "decimal(18, 4)")]
        public decimal? Pfcontribution { get; set; }
        [Column("PFEmployerContribution", TypeName = "decimal(18, 4)")]
        public decimal? PfemployerContribution { get; set; }
        [Column("PFEmployeePercentage", TypeName = "decimal(18, 2)")]
        public decimal? PfemployeePercentage { get; set; }
        [Column("PFEmployerPercentage", TypeName = "decimal(18, 2)")]
        public decimal? PfemployerPercentage { get; set; }
        [Column("isPFVaried")]
        public bool? IsPfvaried { get; set; }
        [Column(TypeName = "decimal(18, 4)")]
        public decimal? BasicSalary { get; set; }
        public int? Supervisor { get; set; }
        public byte[] Photo { get; set; }
        public bool? Authorized { get; set; }
        [Column("AuthorizedByID")]
        public int? AuthorizedById { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? AuthorizedDate { get; set; }
        [Column("CreatedByID")]
        public int? CreatedById { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? CreatedDate { get; set; }
        [Column("LastUpdatedByID")]
        public int? LastUpdatedById { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? LastUpdatedDate { get; set; }
    }
}