// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace PETAS.Models.Domain.HRMS
{
    [Table("Grade")]
    public partial class Grade
    {
        [Key]
        [Column("GradeID")]
        public int GradeId { get; set; }
        [StringLength(50)]
        public string Letter { get; set; }
    }
}