// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace PETAS.Models.Domain.HRMS
{
    [Table("JobTitle")]
    public partial class JobTitle
    {
        [Key]
        [Column("JobTitleID")]
        public int JobTitleId { get; set; }
        [StringLength(50)]
        public string Name { get; set; }
    }
}