// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace PETAS.Models.Domain
{
    [Table("AdmList")]
    public partial class AdmList
    {
        /// <summary>
        /// primary key
        /// </summary>
        [Key]
        [Column("AdminID")]
        public int AdminId { get; set; }
        /// <summary>
        /// the ID of the employee
        /// </summary>
        [Column("EmployeeID")]
        public int? EmployeeId { get; set; }
        /// <summary>
        /// the user name of the employee
        /// </summary>
        [StringLength(50)]
        [Unicode(false)]
        public string UserName { get; set; }
        /// <summary>
        /// the first name of the employee
        /// </summary>
        [StringLength(50)]
        [Unicode(false)]
        public string FirstName { get; set; }
        /// <summary>
        /// the last name of the employee
        /// </summary>
        [StringLength(50)]
        [Unicode(false)]
        public string LastName { get; set; }
        /// <summary>
        /// flag determining if the profile is active or not
        /// </summary>
        public int? IsActive { get; set; }
    }
}