// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace PETAS.Models.Domain
{
    [Table("ObjectiveClass")]
    public partial class ObjectiveClass
    {
        [Key]
        public int Id { get; set; }
        /// <summary>
        /// the Id of the question
        /// </summary>
        [Column("QuestionID")]
        public int? QuestionId { get; set; }
        /// <summary>
        /// objective 1
        /// </summary>
        [Column(TypeName = "text")]
        public string Cobj1 { get; set; }
        /// <summary>
        /// objective 2
        /// </summary>
        [Column(TypeName = "text")]
        public string Cobj2 { get; set; }
        /// <summary>
        /// objective 3
        /// </summary>
        [Column(TypeName = "text")]
        public string Cobj3 { get; set; }
        /// <summary>
        /// objective 4
        /// </summary>
        [Column(TypeName = "text")]
        public string Cobj4 { get; set; }
    }
}