// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace PETAS.Models.Domain
{
    [Table("TrainingDomain")]
    public partial class TrainingDomain
    {
        public TrainingDomain()
        {
            TrainingGroupings = new HashSet<TrainingGrouping>();
        }

        /// <summary>
        /// primary key of the table
        /// </summary>
        [Key]
        public int Id { get; set; }
        /// <summary>
        /// the name of the domain
        /// </summary>
        [StringLength(50)]
        [Unicode(false)]
        public string DomainName { get; set; }
        /// <summary>
        /// the description of the domain
        /// </summary>
        [StringLength(200)]
        [Unicode(false)]
        public string DomainDescription { get; set; }

        [InverseProperty(nameof(TrainingGrouping.Domain))]
        public virtual ICollection<TrainingGrouping> TrainingGroupings { get; set; }
    }
}