// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace PETAS.Models.Domain
{
    [Table("TrainingStatusType")]
    public partial class TrainingStatusType
    {
        public TrainingStatusType()
        {
            Training = new HashSet<Training>();
        }

        [Key]
        public int Id { get; set; }
        [StringLength(50)]
        [Unicode(false)]
        public string TrainingTypeStatus { get; set; }

        [InverseProperty("TrainingStatus")]
        public virtual ICollection<Training> Training { get; set; }
    }
}