// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace PETAS.Data.Models
{
    [Table("AssessmentQuestionPool")]
    public partial class AssessmentQuestionPool
    {
        /// <summary>
        /// primary key of the table entity
        /// </summary>
        [Key]
        public int Id { get; set; }
        /// <summary>
        /// a question for the assessment
        /// </summary>
        [StringLength(1000)]
        [Unicode(false)]
        public string Question { get; set; }
        /// <summary>
        /// question type lookup. foreign key to the dbo.QuestionTypeLookup table
        /// </summary>
        public int? QuestionType { get; set; }
        /// <summary>
        /// foreign key to Training Assessment
        /// </summary>
        [Column("SubjectID")]
        public int? SubjectId { get; set; }
        [Column(TypeName = "date")]
        public DateTime? CreatedDate { get; set; }
        [StringLength(50)]
        [Unicode(false)]
        public string CreatedBy { get; set; }
        [Column(TypeName = "date")]
        public DateTime? AuthorizedDate { get; set; }
        [StringLength(50)]
        [Unicode(false)]
        public string AuthorizedBy { get; set; }

        [ForeignKey(nameof(QuestionType))]
        [InverseProperty("AssessmentQuestionPools")]
        public virtual QuestionType QuestionTypeNavigation { get; set; }
        [ForeignKey(nameof(SubjectId))]
        [InverseProperty(nameof(AssessmentSubject.AssessmentQuestionPools))]
        public virtual AssessmentSubject Subject { get; set; }
    }
}