// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace PETAS.Data.Models
{
    [Table("ObjectiveClass")]
    public partial class ObjectiveClass
    {
        [Key]
        public int Id { get; set; }
        [Column("QuestionID")]
        public int? QuestionId { get; set; }
        [Column(TypeName = "text")]
        public string Cobj1 { get; set; }
        [Column(TypeName = "text")]
        public string Cobj2 { get; set; }
        [Column(TypeName = "text")]
        public string Cobj3 { get; set; }
        [Column(TypeName = "text")]
        public string Cobj4 { get; set; }
    }
}