// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace PETAS.Data.Models
{
    [Table("StaffQuestionAssessment")]
    public partial class StaffQuestionAssessment
    {
        /// <summary>
        /// primary key of the table
        /// </summary>
        [Key]
        public int Id { get; set; }
        /// <summary>
        /// the ID of the question
        /// </summary>
        [Column("QuestionID")]
        public int? QuestionId { get; set; }
        /// <summary>
        /// the marks awarded
        /// </summary>
        public int? MarksAwarded { get; set; }
        /// <summary>
        /// the ID of the training
        /// </summary>
        [Column("TrainingID")]
        public int? TrainingId { get; set; }
        [Column("StaffID")]
        public int? StaffId { get; set; }
    }
}