// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace PETAS.Data.Models
{
    [Table("TrainingGrouping")]
    public partial class TrainingGrouping
    {
        public TrainingGrouping()
        {
            Training = new HashSet<Training>();
        }

        /// <summary>
        /// primary key
        /// </summary>
        [Key]
        public int Id { get; set; }
        /// <summary>
        /// name of group
        /// </summary>
        [StringLength(50)]
        [Unicode(false)]
        public string GroupName { get; set; }
        /// <summary>
        /// description of the group
        /// </summary>
        [StringLength(200)]
        [Unicode(false)]
        public string GroupDescription { get; set; }
        [Column("DomainID")]
        public int? DomainId { get; set; }
        /// <summary>
        /// the date group was created
        /// </summary>
        [Column(TypeName = "date")]
        public DateTime? CreatedDate { get; set; }
        /// <summary>
        /// the user creating the group
        /// </summary>
        [Column("CreatedByID")]
        public int? CreatedById { get; set; }
        [Column(TypeName = "date")]
        public DateTime? AuthorizedDate { get; set; }
        [Column("AuthorizedByID")]
        public int? AuthorizedById { get; set; }
        [Column("LastUpdatedByID")]
        public int? LastUpdatedById { get; set; }
        [Column(TypeName = "date")]
        public DateTime? LastUpdatedDate { get; set; }

        [ForeignKey(nameof(DomainId))]
        [InverseProperty(nameof(TrainingDomain.TrainingGroupings))]
        public virtual TrainingDomain Domain { get; set; }
        [InverseProperty("TrainingGroup")]
        public virtual ICollection<Training> Training { get; set; }
    }
}