// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace PANTrainerAPI.Models
{
    [Table("AssessmentSubject")]
    public partial class AssessmentSubject
    {
        public AssessmentSubject()
        {
            AssessmentQuestionPools = new HashSet<AssessmentQuestionPool>();
        }

        [Key]
        public int Id { get; set; }
        [StringLength(100)]
        [Unicode(false)]
        public string SubjectName { get; set; }

        [InverseProperty(nameof(AssessmentQuestionPool.Subject))]
        public virtual ICollection<AssessmentQuestionPool> AssessmentQuestionPools { get; set; }
    }
}