// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace PANTrainerAPI.Models
{
    [Table("QuestionType")]
    public partial class QuestionType
    {
        public QuestionType()
        {
            AssessmentQuestionPools = new HashSet<AssessmentQuestionPool>();
            Qalloteds = new HashSet<Qalloted>();
        }

        /// <summary>
        /// primary key
        /// </summary>
        [Key]
        public int Id { get; set; }
        /// <summary>
        /// the type of question. (MCANS = Multiple choice questions, WRTANS = written)
        /// </summary>
        [Column("QuestionType")]
        [StringLength(50)]
        [Unicode(false)]
        public string QuestionType1 { get; set; }

        [InverseProperty(nameof(AssessmentQuestionPool.QuestionTypeNavigation))]
        public virtual ICollection<AssessmentQuestionPool> AssessmentQuestionPools { get; set; }
        [InverseProperty(nameof(Qalloted.QuestionType))]
        public virtual ICollection<Qalloted> Qalloteds { get; set; }
    }
}